// <auto-generated />
using System;
using BeeFreeEditor.Core.Abstractions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BeeFreeEditor.Core.Migrations
{
    [DbContext(typeof(EmailTemplateContext))]
    partial class EmailTemplateContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BeeFreeEditor.Core.Abstractions.BeeFreeEmailTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.Property<string>("HtmlData")
                        .IsRequired();

                    b.Property<string>("Language")
                        .IsRequired();

                    b.Property<DateTime>("LastModified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<Guid>("OrganizationId");

                    b.Property<string>("TemplateData")
                        .IsRequired();

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnName("TemplateType");

                    b.HasKey("Id");

                    b.ToTable("EmailTemplates");
                });

            modelBuilder.Entity("BeeFreeEditor.Core.Abstractions.LocationEmailTemplateMap", b =>
                {
                    b.Property<long>("RegistrationLocationId");

                    b.Property<string>("Type")
                        .HasColumnName("TemplateType");

                    b.Property<string>("Language");

                    b.Property<Guid>("EmailTemplateId");

                    b.HasKey("RegistrationLocationId", "Type", "Language");

                    b.HasIndex("EmailTemplateId");

                    b.ToTable("LocationEmailTemplateMap");
                });

            modelBuilder.Entity("BeeFreeEditor.Core.Abstractions.MergeTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("LastModified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<Guid>("OrganizationId");

                    b.Property<string>("Properties");

                    b.HasKey("Id");

                    b.ToTable("MergeTags");
                });

            modelBuilder.Entity("BeeFreeEditor.Core.Abstractions.LocationEmailTemplateMap", b =>
                {
                    b.HasOne("BeeFreeEditor.Core.Abstractions.BeeFreeEmailTemplate", "EmailTemplate")
                        .WithMany()
                        .HasForeignKey("EmailTemplateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
